---   
- name: "Upgrade all and install new packages for RHEL"
  import_tasks: redhat.yml
  when: ansible_facts['os_family']|lower == 'redhat'

- name: "Upgrade all and install new packages for Debian"
  import_tasks: debian.yml
  when: ansible_facts['os_family']|lower == 'debian'