---
- name: "Check if 'wheel' group exists"
  group:
    name: wheel
    state: present

- name: "Allow 'wheel' group to have passwordless sudo"
  lineinfile:
    dest: /etc/sudoers
    state: present
    regexp: '^%wheel'
    line: '%wheel ALL=(ALL) NOPASSWD: ALL'
    validate: 'visudo -cf %s'

- name: "Create new user"
  user:
    name: "{{ new_user_name }}"
    groups: wheel
    append: yes
    state: present
    createhome: yes